before_install:
- openssl aes-256-cbc -K $encrypted_a548230573da_key -iv $encrypted_a548230573da_iv
  -in client-secret.json.enc -out client-secret.json -d
language: node_js
node_js:
  - "7"
deploy:
  provider: gae
  keyfile: client-secret.json
  project: micro-test-small-improvements
  no_promote: true
